name: HexoCI/CD
on: [push]
jobs:
  GenerateAndDeploy:
    runs-on: ubuntu-latest
    steps: 
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          path: "hexo"
      - name: "Initalize Node.JS environment"
        run: |
          sudo apt install nodejs npm curl
          wget -O ./nodejs.tar.xz https://nodejs.org/dist/v16.13.2/node-v16.13.2-linux-x64.tar.xz
          tar -xvf ./nodejs.tar.xz
          cd node-v16.13.2-linux-x64
          sudo cp -R ./* /usr
          sudo npm install -g npm@latest
      - name: "Install Hexo and Generate"
        run: |
          sudo npm install -g hexo-cli
          cd $GITHUB_WORKSPACE/hexo
          hexo clean
          hexo generate
      - name: "Deploy to Github Pages"
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: main
          build_dir: hexo/public
          repo: "LtD0gE/www.ltdoge.top"
          keep_history: true
          allow_empty_commit: false
          commit_message: "Automatic Deploy"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
      - name: "Purge Cloudflare Cache"
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/0463d50990b37f868fc4db6abbd6ae2b/purge_cache" \
          -H "X-Auth-Email: ltdoge@ltdoge.top"      \
          -H "X-Auth-Key: ${{ secrets.CF_API_KEY }}" \
          -H "Content-Type: application/json"      \
          --data '{"purge_everything":true}'
      - name: "Delete Builder Workflow Runs"
        uses: GitRML/delete-workflow-runs@main
        with:
          token: ${{ secrets.GH_PAT }}
          repository: LtD0gE/LtD0gE-hexo-ci-cd
          keep_minimum_runs: 10
      - name: "Delete Page Workflow Runs"
        uses: GitRML/delete-workflow-runs@main
        with:
          token: ${{ secrets.GH_PAT }}
          repository: LtD0gE/www.ltdoge.top
          keep_minimum_runs: 10
