name: HexoCI/CD
on: [push]
jobs:
  GenerateAndDeploy:
    runs-on: ubuntu-latest
    steps: 
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          path: "hexo"
      - name: "Initalize Node.JS environment"
        run: |
          sudo apt install nodejs npm
          wget -O ./nodejs.tar.xz https://nodejs.org/dist/v16.13.2/node-v16.13.2-linux-x64.tar.xz
          tar -xvf ./nodejs.tar.xz
          cd node-v16.13.2-linux-x64
          sudo cp -R ./* /usr
          sudo npm install -g npm@latest
      - name: "Install Hexo,Theme and Generate"
        run: |
          sudo npm install -g hexo-cli
          cd $GITHUB_WORKSPACE/hexo
          sudo npm install --save hexo-theme-fluid
          hexo clean
          hexo generate
      - name: "Deploy to Github Pages"
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: main
          build_dir: hexo/public
          repo: "LtD0gE/www.ltdoge.top"
          keep_history: true
          allow_empty_commit: false
          commit_message: "Automatic Deploy"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}